# Generated by Django 4.2.30 on 2026-09-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credits', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bucket', models.CharField(blank=True, max_length=100, null=True)),
                ('programme_applicability', models.CharField(blank=True, max_length=255, null=True)),
                ('source_metadata', models.JSONField(blank=True, help_text='Metadata about source provenance', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_condition', models.CharField(max_length=255)),
                ('condition_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uncertainty_source_metadata', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_context', models.CharField(blank=True, max_length=100, null=True)),
                ('programme_context', models.CharField(blank=True, max_length=100, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=100, null=True)),
                ('source_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course')),
            ],
        ),
    ]
