# Generated by Django 4.2.30 on 2026-09-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text="e.g. 'Student A'", max_length=50, unique=True)),
                ('programme', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('current_semester', models.IntegerField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('credits_earned', models.FloatField(blank=True, null=True)),
                ('minor_opted', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_completeness_status', models.CharField(default='COMPLETE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('source_profile_metadata', models.JSONField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_history', to='students.student')),
            ],
        ),
    ]
